package com.devicedetection.api;

import com.devicedetection.dao.EventTypRepository;
import com.devicedetection.model.EventTyp;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;


@Controller // This means that this class is a Controller
@RequestMapping(path="/eventtyp") // This means URL's start with /demo (after Application path)
public class EventTypController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private EventTypRepository eventTypRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewEventTyp (@RequestParam String beschreibung
      ){
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    EventTyp n = new EventTyp();
    n.setBeschreibung(beschreibung);
    eventTypRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<EventTyp> getAllEventTypes() {
    // This returns a JSON or XML with the users
    return eventTypRepository.findAll();
  }
}