package com.devicedetection.api;

import com.devicedetection.dao.GeraetEventRepository;
import com.devicedetection.model.GeraetEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Timestamp;


@Controller // This means that this class is a Controller
@RequestMapping(path="/geraetevent") // This means URL's start with /demo (after Application path)
public class GeraetEventController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private GeraetEventRepository geraetEventRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewGeraetEvent (@RequestParam Timestamp datum
      , Integer geraetesignatur_id, Integer eventtyp_id){
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    GeraetEvent n = new GeraetEvent();
    n.setDatum(datum);
    
    geraetEventRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<GeraetEvent> getAllGeraetEvents() {
    // This returns a JSON or XML with the users
    return geraetEventRepository.findAll();
  }
}