package com.devicedetection.api;

import com.devicedetection.dao.GeraetRepository;
import com.devicedetection.model.Geraet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;


@Controller // This means that this class is a Controller
@RequestMapping(path="/geraet") // This means URL's start with /demo (after Application path)
public class GeraetController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private GeraetRepository geraetRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewGeraet (@RequestParam String name
      , @RequestParam String beschreibung
      , @RequestParam Integer raumNr
      , @RequestParam Date datumErstellung) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Geraet n = new Geraet();
    n.setName(name);
    n.setBeschreibung(beschreibung);
    n.setRaumNr(raumNr);
    n.setDatumErstellung(datumErstellung);
    geraetRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Geraet> getAllGeraete() {
    // This returns a JSON or XML with the users
    return geraetRepository.findAll();
  }
}